### Find All Content
GET http://localhost:8080/api/content

### Get Content by Id
GET http://localhost:8080/api/content/1

### Create a new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My Second Blog Post",
  "desc": "My Second Blog Post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-05-26T20:06:54.807347",
  "dateUpdated": null,
  "url": ""
}